### ISSUE TITLE
kicker doesn't wait until cooldown has ended

### ISSUE THREAD

**Issue by TehcJS** [Googe14/tf2-bot-kicker-gui#12]
the kick fail sound gets annoying after a while

**Comment by Googe14** [comment]
Unfortunately I don't believe there is a way to determine this with console commands so I don't think this is a solvable issue. You will just have to turn down the kick frequency if it is getting annoying

**Comment by TehcJS** [comment]
it could detect when the last kick was done and to wait 2 minutes.

**Comment by Googe14** [comment]
This unfortunately does not work as there is no way to check if it successfully calls a votekick, so it could fail because someone else is calling a vote then will wait 2 minutes when it doesn't need to.
