### ISSUE TITLE
Period and Checkboxes don't always update

### ISSUE THREAD

**Issue by TehcJS** [Googe14/tf2-bot-kicker-gui#14]
when turning the alerts on or off or changing the period, it doesn't update and continues putting alerts in chat.

**Comment by Googe14** [comment]
Fixed, will be in next release

**Comment by Googe14** [comment]
Or alternatively you can download the most recent compiled binary from the root directory of the repository itself:
[Linux](https://github.com/Googe14/tf2-bot-kicker-gui/raw/master/tf2-bot-kicker-gui), [Windows](https://github.com/Googe14/tf2-bot-kicker-gui/raw/master/tf2-bot-kicker-gui.exe)
