### ISSUE TITLE
Clarify license

### ISSUE THREAD

**Issue by melvyn2** [Googe14/tf2-bot-kicker-gui#18]
The code is currently unlicensed, which makes it unclear what is allowed and what is not concerning distribution and source code.

**Comment by Googe14** [comment]
Good point, I will do that at the soonest opportune moment.

**Comment by 2l47** [comment]
> Good point, I will do that at the soonest opportune moment.

@Googe14 Hey, I just wanted to suggest using either the [Unlicense](https://unlicense.org/) or the [MIT License](https://opensource.org/licenses/MIT) so that others can freely make their own improvements.

**Comment by Googe14** [comment]
Added MIT license
