### ISSUE TITLE
make an option to add steam id or name to custom txt or json file

### ISSUE THREAD

**Issue by TehcJS** [Googe14/tf2-bot-kicker-gui#3]
i want to put cheaters in cheaters.txt and imposter bots in imposters.txt
![image](https://user-images.githubusercontent.com/18603248/150421390-e23ae26c-7c33-4ee7-ac42-53b39894bfe9.png)

**Comment by Googe14** [comment]
I will add a setting to choose which file the program will add steamids or regexes to.

**Comment by Googe14** [comment]
Implemented, will be in next release
