### ISSUE TITLE
add ability to set reason for marking as bot when saving id or name

### ISSUE THREAD

**Issue by TehcJS** [Googe14/tf2-bot-kicker-gui#4]

**Comment by Googe14** [comment]
Not sure if it is quite what you are after, but I have allowed the user to modify the name regex and steamid message before adding it to the file. At least with the SteamID that means you can add a not that will show up in the file, however this does not apply so much for the regex. If this isn't quite what you are after then open another issue and I will consider if it is something I would like to add.
