### ISSUE TITLE
send keypress directly to tf2 application

### ISSUE THREAD

**Issue by TehcJS** [Googe14/tf2-bot-kicker-gui#6]
send keypress directly to tf2 application so you can alt+tab without pausing the bot kicker

**Comment by Googe14** [comment]
Initially I thought this would not be possible while keeping compatibility across platforms, however I am investigating a way to do this using RCon which would remove the need to send commands via keypress at all. This may be in a future release.

**Comment by Googe14** [comment]
Implemented, will be in next release.
